# Generated by Django 6.0.1 on 2026-01-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('parameter', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=10)),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('region', 'parameter', 'year', 'month')},
            },
        ),
    ]
