# Generated by Django 6.0.1 on 2026-01-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='parameter',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='region',
            field=models.CharField(max_length=40),
        ),
    ]
